server:
  port: 8012
spring:
  application:
    name: cloudconfigserver
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          password: '{cipher}AQAWjroFaPctotbDxGgIDdEE2t4xYZv5OCZ7Jzip0lTCukH8NTAwz6NRjlo7GE9wFo5+9jUTuiYgV0ylo/2C2pT//9mM6p53gw2QZ72+VU+vnQIHmWih/+rwJWpfBvbj2110i9dV7Vk/qLqMP2wQ9Gm+ErIGwJHU86sSzwrdAY+WUoqE8lzl+LWDfGZ7J/KhQhbzsC72aTs25SgonxwqLNkhYM8ZzaW95Fjxjx5MjQNcYsr+U7cCGmWkX1vvy5Lbl7ekUms7/QTtBkyR3LaARyQGg/ATnITBJvVCRQtfoWtaKUDiEaPpdArkwvBWdSR0J62GCMafHI4WVDzEdfPgZJAeankrig1WyG1HCBZi7mm/nFWhjBYpg+TVlOqCjcz0qu4='
          uri: https://github.com/biswajit-prog1990/configurationdb
          username: '{cipher}AQCC/cnbaQk5wgU19TnbYTo+Vw9o9g6PCXBPkSodBQe1R6w+DHRr+UqXTJPfIY8cZ8s5xRXHid7Nautf9IPN23I2U33tC6TpmOpuYyBo0QX6ZUpdMVkvwJbVPve/ODIVlPxJnyMfo2FezGjZQPEmxe7IbGlx42u9/DcNnhPt/rlKtHkirprOqwXTIrRa1MlCZs2hAZjUasN5Chx17BZV/ULJsbB+HEUKJjYxmDNzys0KvYRNBYnHUP37Srtky4A9ZVRKF43Xe5//1x3NnMZOubydKkWHZc1WTShxiOpcTddkXuE4FSYVg9cNvVHb7IU5syKzH+Wn+BTJEMPQbt6w3+d+LI+gZRjBWpy8YrhR8693NUxrxctFnVB9zL68u35ZC+BJpISyHVdVkcxwMq5s6168'
  rabbitmq:
    host: localhost
    port: 5672
    username: '{cipher}AQCU4wcEd93Mw+GXpQgADPxqVYT7yStZ0tU+ad8p5x42rnYjJDcq2ZipV8eTA6nW91XLs1JLdSR0qccpHIjSfEF22PVYiPJQUGCY9nN+j1qNEDUYzdONVdki7wl2bRCSKDmzbotebt/sCSpSNQqGfbfVUmmjn4cvPwNBZOiCt9hDZnOowhU4K9GO2fYH4YIi05OWtHNYiRWLUb5tUiBXVTNESR9OAtOGL8oFGWNad8IoNbjjnFVwV2eFPxJHF2SFIEf2T3QsvY3O2DwqqdRfK+28kWrbHyqiVPuCYd/45OsXL4a6sG67HiW0RCZbGKuWJRDkPyQLNxjiJHb4260nyI/j6D3VoZyS0wSIoycX59ez1OhoC+l2WWkE5ADEigTmnLE='
    password: '{cipher}AQBCaZ4zbcXoltci9pS71QorAC9JERIg1ijvvB2ckH4Xu7iDi8hXNxaxn1tUBlFHVj3WPRTr6sinWHhu+koFR3TWHHe/ilKp+ikjDqQhKKn3CGDAjPHsBy1SdaxYYihmRWh3iff9KrTMGo3daOTbTuKUGbRQjwvtSDq+V8iQm2XgDsFU60e7vD3FtXr8dB0OOns5i2Yl8gt5hV7fc8wFtJEl7davUctku6w0oyZTYMy+Y9n6gOW1+Oy7nIsa8DZjIxahGMyCMTcbl06+6qYxMSoHyR+cChoMhrZduroy7nlXMJ7ZqZJmR7g3uR8rNrFy3I7FgSIlnX5fQtPcUlsFjugYAgOWE1Q+GDT3gBPUKysSqN/kFM57u40GO/FBRZHyaY4='
management:
  endpoints:
    web:
      exposure:
        include:
        - bus-refresh